'use strict';

const reactEventNames = {
  'abort':              'onAbort',
  'animationend':       'onAnimationEnd',
  'animationiteration': 'onAnimationIteration',
  'animationstart':     'onAnimationStart',
  'blur':               'onBlur',
  'canplay':            'onCanPlay',
  'canplaythrough':     'onCanPlayThrough',
  'change':             'onChange',
  'click':              'onClick',
  'compositionend':     'onCompositionEnd',
  'compositionstart':   'onCompositionStart',
  'compositionupdate':  'onCompositionUpdate',
  'contextmenu':        'onContextMenu',
  'copy':               'onCopy',
  'cut':                'onCut',
  'doubleclick':        'onDoubleClick',
  'drag':               'onDrag',
  'dragend':            'onDragEnd',
  'dragenter':          'onDragEnter',
  'dragexit':           'onDragExit',
  'dragleave':          'onDragLeave',
  'dragover':           'onDragOver',
  'dragstart':          'onDragStart',
  'drop':               'onDrop',
  'durationchange':     'onDurationChange',
  'emptied':            'onEmptied',
  'encrypted':          'onEncrypted',
  'ended':              'onEnded',
  'error':              'onError',
  'focus':              'onFocus',
  'gotpointercapture':  'onGotPointerCapture',
  'input':              'onInput',
  'invalid':            'onInvalid',
  'keydown':            'onKeyDown',
  'keypress':           'onKeyPress',
  'keyup':              'onKeyUp',
  'load':               'onLoad',
  'loadeddata':         'onLoadedData',
  'loadedmetadata':     'onLoadedMetadata',
  'loadstart':          'onLoadStart',
  'lostpointercapture': 'onLostPointerCapture',
  'mousedown':          'onMouseDown',
  'mouseenter':         'onMouseEnter',
  'mouseleave':         'onMouseLeave',
  'mousemove':          'onMouseMove',
  'mouseout':           'onMouseOut',
  'mouseover':          'onMouseOver',
  'mouseup':            'onMouseUp',
  'paste':              'onPaste',
  'pause':              'onPause',
  'play':               'onPlay',
  'playing':            'onPlaying',
  'pointercancel':      'onPointerCancel',
  'pointerdown':        'onPointerDown',
  'pointerenter':       'onPointerEnter',
  'pointerleave':       'onPointerLeave',
  'pointermove':        'onPointerMove',
  'pointerout':         'onPointerOut',
  'pointerover':        'onPointerOver',
  'pointerup':          'onPointerUp',
  'progress':           'onProgress',
  'ratechange':         'onRateChange',
  'reset':              'onReset',
  'scroll':             'onScroll',
  'seeked':             'onSeeked',
  'seeking':            'onSeeking',
  'select':             'onSelect',
  'stalled':            'onStalled',
  'submit':             'onSubmit',
  'suspend':            'onSuspend',
  'timeupdate':         'onTimeUpdate',
  'toggle':             'onToggle',
  'touchcancel':        'onTouchCancel',
  'touchend':           'onTouchEnd',
  'touchmove':          'onTouchMove',
  'touchstart':         'onTouchStart',
  'transitionend':      'onTransitionEnd',
  'volumechange':       'onVolumeChange',
  'waiting':            'onWaiting',
  'mousewheel':         'onWheel',
};

function convertToReactEventName(eventName) {
  let reactEventName = reactEventNames[eventName];
  if (!reactEventName)
    return eventName;

  return reactEventName;
}

module.exports = {
  convertToReactEventName,
};
